// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM0ryrSpS2tWxiIuOSSpvjNu3ZdcqsAxA',
    appId: '1:47724503249:web:4f6e4a6cfd7009a8e925f0',
    messagingSenderId: '47724503249',
    projectId: 'greenngo-543b9',
    authDomain: 'greenngo-543b9.firebaseapp.com',
    databaseURL: 'https://greenngo-543b9-default-rtdb.firebaseio.com',
    storageBucket: 'greenngo-543b9.appspot.com',
    measurementId: 'G-8BLNTL53V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsZry3_dbWGDzmnt38ifOAvEf0vjImuM',
    appId: '1:47724503249:android:7fdb0170d68c5550e925f0',
    messagingSenderId: '47724503249',
    projectId: 'greenngo-543b9',
    databaseURL: 'https://greenngo-543b9-default-rtdb.firebaseio.com',
    storageBucket: 'greenngo-543b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI1-1t9gqsCp82UCYDTV5dams-LWdRNzE',
    appId: '1:47724503249:ios:6f16b351df76f294e925f0',
    messagingSenderId: '47724503249',
    projectId: 'greenngo-543b9',
    databaseURL: 'https://greenngo-543b9-default-rtdb.firebaseio.com',
    storageBucket: 'greenngo-543b9.appspot.com',
    iosClientId: '47724503249-ppkgql7j9u21hnpjlppt0smumosefiju.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenNGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI1-1t9gqsCp82UCYDTV5dams-LWdRNzE',
    appId: '1:47724503249:ios:6f16b351df76f294e925f0',
    messagingSenderId: '47724503249',
    projectId: 'greenngo-543b9',
    databaseURL: 'https://greenngo-543b9-default-rtdb.firebaseio.com',
    storageBucket: 'greenngo-543b9.appspot.com',
    iosClientId: '47724503249-ppkgql7j9u21hnpjlppt0smumosefiju.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenNGo',
  );
}
